global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8002']  # Custom metrics (enqueued)
  
  - job_name: 'api-fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']  # FastAPI metrics (requests, latency)
  
  - job_name: 'workers'
    metrics_path: /metrics
    static_configs:
      - targets: ['workers:8001']  # Worker metrics (processed)
